version: "3"
services:
  backend:
    env_file:
      - ./backend/.env
    container_name: blackjack-backend
    build: ./backend
    ports:
      - "$PORT:$PORT"
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"

networks:
  default:
    name: blackjack-network